# Generated by Django 3.2.7 on 2022-11-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceManagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300)),
                ('user_name', models.CharField(max_length=300)),
                ('user_number', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qr', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'ordering': ('site_name',),
            },
        ),
    ]
