# Generated by Django 3.2.7 on 2022-11-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_devicemanagment_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemanagment',
            options={'ordering': ('site_name',)},
        ),
    ]
