# Generated by Django 3.2.7 on 2022-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_devicemanagment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemanagment',
            name='user_number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
