# Generated by Django 3.2.7 on 2022-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_devicemanagment_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemanagment',
            name='user_number',
            field=models.CharField(max_length=300),
        ),
    ]
